check installation

diff --git a/.github/workflows/publish.yml b/.github/workflows/publish.yml
--- a/.github/workflows/publish.yml
+++ b/.github/workflows/publish.yml
@@ -17,6 +17,11 @@ jobs:
       - name: install-test
         run: |
           pip3 install .
+          instaled=$( pip3 list | awk '/^utils_esantix/' )
+          if [ -z "installed" ]; then
+            echo "utils_esantix not found on pip list"
+            exit 1
+          fi
           yes | pip3 uninstall utils_esantix
   release:
     needs: test
